const stateInfo = {
    '01': {
        'name': 'Alabama',
        'ISO': 'US-AL',
        'lat': 32.778,
        'lng': -86.929,
        'zoomLevel': 8,
    },
    '02': {
        'name': 'Alaska',
        'ISO': 'US-AK',
        'lat': 64.061,
        'lng': -152.231,
        'zoomLevel': 4,
    },
    '04': {
        'name': 'Arizona',
        'ISO': 'US-AZ',
        'lat': 34.274,
        'lng': -111.658,
        'zoomLevel': 6,
    },
    '05': {
        'name': 'Arkansas',
        'ISO': 'US-AR',
        'lat': 34.894,
        'lng': -92.4429,
        'zoomLevel': 7,
    },
    '06': {
        'name': 'California',
        'ISO': 'US-CA',
        'lat': 38,
        'lng': -120,
        'zoomLevel': 6,
    },
    '08': {
        'name': 'Colorado',
        'ISO': 'US-CO',
        'lat': 38.998,
        'lng': -105.549,
        'zoomLevel': 7,
    },
    '09': {
        'name': 'Connecticut',
        'ISO': 'US-CT',
        'lat': 41.622,
        'lng': -72.727,
        'zoomLevel': 9,
    },
    '10': {
        'name': 'Delaware',
        'ISO': 'US-DE',
        'lat': 38.989,
        'lng': -75.505,
        'zoomLevel': 8,
    },
    '11': {
        'name': 'District of Columbia',
        'ISO': 'US-DC',
        'lat': 38.910,
        'lng': -77.015,
        'zoomLevel': 12,
    },
    '12': {
        'name': 'Florida',
        'ISO': 'US-FL',
        'lat': 28.628,
        'lng': -82.443,
        'zoomLevel': 6,
    },
    '13': {
        'name': 'Georgia',
        'ISO': 'US-GA',
        'lat': 32.644,
        'lng': -83.442,
        'zoomLevel': 7,
    },
    '15': {
        'name': 'Hawaii',
        'ISO': 'US-HI',
        'lat': 20.295,
        'lng': -156.372,
        'zoomLevel': 7,
    },
    '16': {
        'name': 'Idaho',
        'ISO': 'US-ID',
        'lat': 44.354,
        'lng': -114.609,
        'zoomLevel': 6,
    },
    '17': {
        'name': 'Illinois',
        'ISO': 'US-IL',
        'lat': 40.041,
        'lng': -89.197,
        'zoomLevel': 6,
    },
    '18': {
        'name': 'Indiana',
        'ISO': 'US-IN',
        'lat': 39.894,
        'lng': -86.282,
        'zoomLevel': 7,
    },
    '19': {
        'name': 'Iowa',
        'ISO': 'US-IA',
        'lat': 42.075,
        'lng': -93.496,
        'zoomLevel': 7,
    },
    '20': {
        'name': 'Kansas',
        'ISO': 'US-KS',
        'lat': 38.495,
        'lng': -98.380,
        'zoomLevel': 7,
    },
    '21': {
        'name': 'Kentucky',
        'ISO': 'US-KY',
        'lat': 37.536,
        'lng': -85.302,
        'zoomLevel': 7,
    },
    '22': {
        'name': 'Louisiana',
        'ISO': 'US-LA',
        'lat': 31.069,
        'lng': -91.995,
        'zoomLevel': 7,
    },
    '23': {
        'name': 'Maine',
        'ISO': 'US-ME',
        'lat': 45.370,
        'lng': -69.244,
        'zoomLevel': 6,
    },
    '24': {
        'name': 'Maryland',
        'ISO': 'US-MD',
        'lat': 39.055,
        'lng': -76.791,
        'zoomLevel': 6,
    },
    '25': {
        'name': 'Massachusetts',
        'ISO': 'US-MA',
        'lat': 42.260,
        'lng': -71.808,
        'zoomLevel': 6,
    },
    '26': {
        'name': 'Michigan',
        'ISO': 'US-MI',
        'lat': 44.346,
        'lng': -85.411,
        'zoomLevel': 6,
    },
    '27': {
        'name': 'Minnesota',
        'ISO': 'US-MN',
        'lat': 46.281,
        'lng': -94.305,
        'zoomLevel': 6,
    },
    '28': {
        'name': 'Mississippi',
        'ISO': 'US-MS',
        'lat': 32.735,
        'lng': -89.668,
        'zoomLevel': 6,
    },
    '29': {
        'name': 'Missouri',
        'ISO': 'US-MO',
        'lat': 38.357,
        'lng': -92.457,
        'zoomLevel': 6,
    },
    '30': {
        'name': 'Montana',
        'ISO': 'US-MT',
        'lat': 47.053,
        'lng': -109.645,
        'zoomLevel': 6,
    },
    '31': {
        'name': 'Nebraska',
        'ISO': 'US-NE',
        'lat': 41.539,
        'lng': -99.797,
        'zoomLevel': 6,
    },
    '32': {
        'name': 'Nevada',
        'ISO': 'US-NV',
        'lat': 39.331,
        'lng': -116.627,
        'zoomLevel': 6,
    },
    '33': {
        'name': 'New Hampshire',
        'ISO': 'US-NH',
        'lat': 43.681,
        'lng': -71.582,
        'zoomLevel': 6,
    },
    '34': {
        'name': 'New Jersey',
        'ISO': 'US-NJ',
        'lat': 40.25,
        'lng': -75,
        'zoomLevel': 8,
    },
    '35': {
        'name': 'New Mexico',
        'ISO': 'US-NM',
        'lat': 34.067,
        'lng': -106.113,
        'zoomLevel': 6,
    },
    '36': {
        'name': 'New York',
        'ISO': 'US-NY',
        'lat': 42.954,
        'lng': -75.526,
        'zoomLevel': 6,
    },
    '37': {
        'name': 'North Carolina',
        'ISO': 'US-NC',
        'lat': 35.558,
        'lng': -79.386,
        'zoomLevel': 6,
    },
    '38': {
        'name': 'North Dakota',
        'ISO': 'US-ND',
        'lat': 47.445,
        'lng': -100.467,
        'zoomLevel': 6,
    },
    '39': {
        'name': 'Ohio',
        'ISO': 'US-OH',
        'lat': 40.286,
        'lng': -82.794,
        'zoomLevel': 6,
    },
    '40': {
        'name': 'Oklahoma',
        'ISO': 'US-OK',
        'lat': 35.591,
        'lng': -97.494,
        'zoomLevel': 6,
    },
    '41': {
        'name': 'Oregon',
        'ISO': 'US-OR',
        'lat': 43.934,
        'lng': -120.562,
        'zoomLevel': 6,
    },
    '42': {
        'name': 'Pennsylvania',
        'ISO': 'US-PA',
        'lat': 40.879,
        'lng': -77.799,
        'zoomLevel': 6,
    },
    '44': {
        'name': 'Rhode Island',
        'ISO': 'US-RI',
        'lat': 41.676,
        'lng': -71.556,
        'zoomLevel': 6,
    },
    '45': {
        'name': 'South Carolina',
        'ISO': 'US-SC',
        'lat': 33.917,
        'lng': -80.896,
        'zoomLevel': 6,
    },
    '46': {
        'name': 'South Dakota',
        'ISO': 'US-SD',
        'lat': 44.445,
        'lng': -100.228,
        'zoomLevel': 6,
    },
    '47': {
        'name': 'Tennessee',
        'ISO': 'US-TN',
        'lat': 35.861,
        'lng': -86.350,
        'zoomLevel': 6,
    },
    '48': {
        'name': 'Texas',
        'ISO': 'US-TX',
        'lat': 31.479,
        'lng': -99.329,
        'zoomLevel': 6,
    },
    '49': {
        'name': 'Utah',
        'ISO': 'US-UT',
        'lat': 39.306,
        'lng': -111.669,
        'zoomLevel': 6,
    },
    '50': {
        'name': 'Vermont',
        'ISO': 'US-VT',
        'lat': 44.069,
        'lng': -72.666,
        'zoomLevel': 6,
    },
    '51': {
        'name': 'Virginia',
        'ISO': 'US-VA',
        'lat': 37.523,
        'lng': -78.853,
        'zoomLevel': 6,
    },
    '53': {
        'name': 'Washington',
        'ISO': 'US-WA',
        'lat': 47.382,
        'lng': -120.451,
        'zoomLevel': 6,
    },
    '54': {
        'name': 'West Virginia',
        'ISO': 'US-WV',
        'lat': 38.641,
        'lng': -80.623,
        'zoomLevel': 6,
    },
    '55': {
        'name': 'Wisconsin',
        'ISO': 'US-WI',
        'lat': 44.624,
        'lng': -89.994,
        'zoomLevel': 6,
    },
    '56': {
        'name': 'Wyoming',
        'ISO': 'US-WY',
        'lat': 42.996,
        'lng': -107.553,
        'zoomLevel': 6,
    },
    '72': {
        'name': 'Puerto Rico',
        'ISO': 'US-PR',
        'lat': 0,
        'lng': 0,
        'zoomLevel': 1,
    },
};
